"""
Reference data pools for the CareerBridge seed engine.

This module is the single source of truth for realistic, real-world reference
data used across the seed generators (companies, universities, locations,
synthetic-company naming). Keeping these pools here (instead of buried as
inline literals inside seed_engine.py) makes it easy for future maintainers to
extend scale/diversity without touching generator logic.

Sections:
  1. PUBLIC_COMPANY_REFERENCES - real, well-known companies across industries
  2. UNIVERSITY_DATA           - real universities (US/India/UK/Canada/Australia)
  3. UNIVERSITY_POOL           - flat name tuple derived from UNIVERSITY_DATA
                                 (kept for backward-compatible sampling call sites)
  4. COUNTRY_CITY_MAP          - city pools per country for synthetic companies/jobs
  5. SYNTHETIC_COMPANY_PREFIXES / SUFFIXES - name-generation pools for the
                                 synthetic companies that pad out the roster
                                 beyond the real-company references above
"""

from __future__ import annotations

# ================================================================================
# 1. PUBLIC COMPANY REFERENCES
# Real, well-known companies spanning big tech, Indian IT services, startups,
# finance, healthcare, retail, consulting, manufacturing, media, biotech, and
# government-adjacent / public-sector-facing organizations.
# Schema per entry (all consumed by CompanyGenerator._build_reference_company):
#   name, legal_name, industry, website, career_page, headquarters_city,
#   headquarters_country, description, founded_year, company_size,
#   employee_count_range (tuple), is_public, specialties (tuple)
# ================================================================================

PUBLIC_COMPANY_REFERENCES: tuple[dict[str, object], ...] = (
    # --- Indian IT services / product ---
    {'name': 'Infosys', 'legal_name': 'Infosys Limited', 'industry': 'Enterprise IT', 'website': 'https://www.infosys.com', 'career_page': 'https://www.infosys.com/careers.html', 'headquarters_city': 'Bengaluru', 'headquarters_country': 'India', 'description': 'Infosys is a global technology services company known for digital transformation, consulting, and large-scale enterprise delivery across industries.', 'founded_year': 1981, 'company_size': 'Enterprise', 'employee_count_range': (317000, 343000), 'is_public': True, 'specialties': ('Cloud modernization', 'AI services', 'Digital engineering', 'Enterprise consulting')},
    {'name': 'Tata Consultancy Services', 'legal_name': 'Tata Consultancy Services Limited', 'industry': 'Enterprise IT', 'website': 'https://www.tcs.com', 'career_page': 'https://www.tcs.com/careers', 'headquarters_city': 'Mumbai', 'headquarters_country': 'India', 'description': 'TCS provides IT services, consulting, and business solutions for large enterprises with a strong focus on delivery excellence and global talent development.', 'founded_year': 1968, 'company_size': 'Enterprise', 'employee_count_range': (590000, 620000), 'is_public': True, 'specialties': ('IT services', 'Consulting', 'Cloud transformation', 'Data and analytics')},
    {'name': 'Wipro', 'legal_name': 'Wipro Limited', 'industry': 'Enterprise IT', 'website': 'https://www.wipro.com', 'career_page': 'https://careers.wipro.com', 'headquarters_city': 'Bengaluru', 'headquarters_country': 'India', 'description': 'Wipro delivers consulting, engineering, and managed services for enterprises seeking modernization, automation, and resilient digital operations.', 'founded_year': 1945, 'company_size': 'Enterprise', 'employee_count_range': (220000, 250000), 'is_public': True, 'specialties': ('Engineering services', 'Cloud', 'Cybersecurity', 'Managed services')},
    {'name': 'HCLTech', 'legal_name': 'HCL Technologies Limited', 'industry': 'Enterprise IT', 'website': 'https://www.hcltech.com', 'career_page': 'https://www.hcltech.com/careers', 'headquarters_city': 'Noida', 'headquarters_country': 'India', 'description': 'HCLTech provides engineering, digital, and cloud services to global enterprises, with deep expertise in software product engineering.', 'founded_year': 1976, 'company_size': 'Enterprise', 'employee_count_range': (220000, 230000), 'is_public': True, 'specialties': ('Engineering R&D', 'Cloud', 'Digital transformation', 'IoT')},
    {'name': 'Tech Mahindra', 'legal_name': 'Tech Mahindra Limited', 'industry': 'Enterprise IT', 'website': 'https://www.techmahindra.com', 'career_page': 'https://careers.techmahindra.com', 'headquarters_city': 'Pune', 'headquarters_country': 'India', 'description': 'Tech Mahindra specializes in digital transformation, consulting, and business re-engineering for telecom and enterprise customers.', 'founded_year': 1986, 'company_size': 'Enterprise', 'employee_count_range': (145000, 155000), 'is_public': True, 'specialties': ('Telecom software', 'Network engineering', '5G', 'Digital consulting')},
    {'name': 'Zoho', 'legal_name': 'Zoho Corporation Private Limited', 'industry': 'SaaS', 'website': 'https://www.zoho.com', 'career_page': 'https://www.zoho.com/careers.html', 'headquarters_city': 'Chennai', 'headquarters_country': 'India', 'description': 'Zoho builds a broad portfolio of business software products spanning CRM, productivity, finance, collaboration, and developer tools.', 'founded_year': 1996, 'company_size': 'Large', 'employee_count_range': (12000, 17000), 'is_public': False, 'specialties': ('Business software', 'CRM', 'Collaboration tools', 'Developer platform')},
    {'name': 'Freshworks', 'legal_name': 'Freshworks Inc.', 'industry': 'SaaS', 'website': 'https://www.freshworks.com', 'career_page': 'https://www.freshworks.com/company/careers/', 'headquarters_city': 'San Mateo', 'headquarters_country': 'United States', 'description': 'Freshworks delivers customer and employee experience software with modern support, CRM, ITSM, and service operations products.', 'founded_year': 2010, 'company_size': 'Mid-Market', 'employee_count_range': (4500, 6500), 'is_public': True, 'specialties': ('Customer support software', 'CRM', 'ITSM', 'SaaS operations')},
    {'name': 'Zerodha', 'legal_name': 'Zerodha Broking Limited', 'industry': 'Fintech', 'website': 'https://zerodha.com', 'career_page': 'https://zerodha.com/careers', 'headquarters_city': 'Bengaluru', 'headquarters_country': 'India', 'description': 'Zerodha is India’s largest discount brokerage, building trading and investment platforms used by millions of retail investors.', 'founded_year': 2010, 'company_size': 'Mid-Market', 'employee_count_range': (1300, 1800), 'is_public': False, 'specialties': ('Trading platforms', 'Fintech infrastructure', 'Risk systems', 'Investment tech')},
    {'name': 'Razorpay', 'legal_name': 'Razorpay Software Private Limited', 'industry': 'Fintech', 'website': 'https://razorpay.com', 'career_page': 'https://razorpay.com/jobs/', 'headquarters_city': 'Bengaluru', 'headquarters_country': 'India', 'description': 'Razorpay provides payment gateway, banking, and financial infrastructure for businesses across India.', 'founded_year': 2014, 'company_size': 'Growth', 'employee_count_range': (2500, 3500), 'is_public': False, 'specialties': ('Payments', 'Banking infrastructure', 'Fintech APIs', 'Risk and fraud')},
    {'name': 'Swiggy', 'legal_name': 'Bundl Technologies Private Limited', 'industry': 'Consumer Internet', 'website': 'https://www.swiggy.com', 'career_page': 'https://careers.swiggy.com', 'headquarters_city': 'Bengaluru', 'headquarters_country': 'India', 'description': 'Swiggy operates a large-scale food delivery and quick-commerce platform serving millions of customers across India.', 'founded_year': 2014, 'company_size': 'Large', 'employee_count_range': (5000, 7000), 'is_public': True, 'specialties': ('Logistics tech', 'Marketplace systems', 'Quick commerce', 'Consumer apps')},
    {'name': 'Flipkart', 'legal_name': 'Flipkart Internet Private Limited', 'industry': 'E-commerce', 'website': 'https://www.flipkart.com', 'career_page': 'https://www.flipkartcareers.com', 'headquarters_city': 'Bengaluru', 'headquarters_country': 'India', 'description': 'Flipkart is one of India’s largest e-commerce platforms, operating marketplace, logistics, and payments businesses at scale.', 'founded_year': 2007, 'company_size': 'Enterprise', 'employee_count_range': (30000, 45000), 'is_public': False, 'specialties': ('E-commerce', 'Supply chain tech', 'Marketplace platforms', 'Logistics')},
    {'name': 'Ola', 'legal_name': 'ANI Technologies Private Limited', 'industry': 'Mobility', 'website': 'https://www.olacabs.com', 'career_page': 'https://www.olacabs.com/careers', 'headquarters_city': 'Bengaluru', 'headquarters_country': 'India', 'description': 'Ola builds ride-hailing, mobility, and electric vehicle platforms serving urban transportation needs across India.', 'founded_year': 2010, 'company_size': 'Large', 'employee_count_range': (8000, 12000), 'is_public': False, 'specialties': ('Mobility platforms', 'Electric vehicles', 'Maps and routing', 'Fleet tech')},
    {'name': 'PhonePe', 'legal_name': 'PhonePe Private Limited', 'industry': 'Fintech', 'website': 'https://www.phonepe.com', 'career_page': 'https://www.phonepe.com/careers/', 'headquarters_city': 'Bengaluru', 'headquarters_country': 'India', 'description': 'PhonePe operates one of India’s largest digital payments platforms, processing billions of transactions across UPI and financial services.', 'founded_year': 2015, 'company_size': 'Large', 'employee_count_range': (3000, 4500), 'is_public': False, 'specialties': ('UPI payments', 'Digital wallets', 'Financial services', 'Merchant platforms')},

    # --- Big tech / global software ---
    {'name': 'Google', 'legal_name': 'Google LLC', 'industry': 'Software', 'website': 'https://about.google', 'career_page': 'https://www.google.com/about/careers/applications/', 'headquarters_city': 'Mountain View', 'headquarters_country': 'United States', 'description': 'Google builds products and platforms in search, advertising, cloud, collaboration, mobile, and AI for consumers and enterprises worldwide.', 'founded_year': 1998, 'company_size': 'Enterprise', 'employee_count_range': (175000, 190000), 'is_public': True, 'specialties': ('Cloud', 'AI', 'Consumer internet', 'Developer platforms')},
    {'name': 'Microsoft', 'legal_name': 'Microsoft Corporation', 'industry': 'Software', 'website': 'https://www.microsoft.com', 'career_page': 'https://careers.microsoft.com', 'headquarters_city': 'Redmond', 'headquarters_country': 'United States', 'description': 'Microsoft develops cloud platforms, enterprise software, developer tools, AI systems, and productivity products used across the world.', 'founded_year': 1975, 'company_size': 'Enterprise', 'employee_count_range': (215000, 235000), 'is_public': True, 'specialties': ('Cloud computing', 'Enterprise software', 'Developer tools', 'AI')},
    {'name': 'Amazon', 'legal_name': 'Amazon.com, Inc.', 'industry': 'E-commerce', 'website': 'https://www.amazon.com', 'career_page': 'https://www.amazon.jobs', 'headquarters_city': 'Seattle', 'headquarters_country': 'United States', 'description': 'Amazon operates global e-commerce, cloud infrastructure, logistics, and digital services platforms at massive scale.', 'founded_year': 1994, 'company_size': 'Enterprise', 'employee_count_range': (1450000, 1600000), 'is_public': True, 'specialties': ('E-commerce', 'Cloud infrastructure', 'Logistics technology', 'Marketplace systems')},
    {'name': 'Meta', 'legal_name': 'Meta Platforms, Inc.', 'industry': 'Media Technology', 'website': 'https://about.meta.com', 'career_page': 'https://www.metacareers.com', 'headquarters_city': 'Menlo Park', 'headquarters_country': 'United States', 'description': 'Meta builds social technology products, communication platforms, developer ecosystems, and AI-driven consumer experiences.', 'founded_year': 2004, 'company_size': 'Enterprise', 'employee_count_range': (65000, 80000), 'is_public': True, 'specialties': ('Consumer internet', 'AI', 'Ads platform', 'Social technology')},
    {'name': 'Netflix', 'legal_name': 'Netflix, Inc.', 'industry': 'Media Technology', 'website': 'https://www.netflix.com', 'career_page': 'https://jobs.netflix.com', 'headquarters_city': 'Los Gatos', 'headquarters_country': 'United States', 'description': 'Netflix operates a global streaming platform powered by large-scale personalization, content systems, and cloud-native engineering.', 'founded_year': 1997, 'company_size': 'Large', 'employee_count_range': (11000, 16000), 'is_public': True, 'specialties': ('Streaming', 'Recommendation systems', 'Cloud-native platforms', 'Media delivery')},
    {'name': 'Apple', 'legal_name': 'Apple Inc.', 'industry': 'Consumer Electronics', 'website': 'https://www.apple.com', 'career_page': 'https://jobs.apple.com', 'headquarters_city': 'Cupertino', 'headquarters_country': 'United States', 'description': 'Apple designs consumer hardware, operating systems, and services spanning mobile, wearables, and cloud ecosystems.', 'founded_year': 1976, 'company_size': 'Enterprise', 'employee_count_range': (160000, 170000), 'is_public': True, 'specialties': ('Hardware engineering', 'iOS platform', 'Silicon design', 'Consumer services')},
    {'name': 'Adobe', 'legal_name': 'Adobe Inc.', 'industry': 'Software', 'website': 'https://www.adobe.com', 'career_page': 'https://careers.adobe.com', 'headquarters_city': 'San Jose', 'headquarters_country': 'United States', 'description': 'Adobe builds creative, document, and marketing software used by creators and enterprises worldwide.', 'founded_year': 1982, 'company_size': 'Enterprise', 'employee_count_range': (28000, 32000), 'is_public': True, 'specialties': ('Creative Cloud', 'Digital experience', 'Document services', 'AI-assisted design')},
    {'name': 'Salesforce', 'legal_name': 'Salesforce, Inc.', 'industry': 'SaaS', 'website': 'https://www.salesforce.com', 'career_page': 'https://careers.salesforce.com', 'headquarters_city': 'San Francisco', 'headquarters_country': 'United States', 'description': 'Salesforce provides customer relationship management and enterprise cloud software across sales, service, and marketing.', 'founded_year': 1999, 'company_size': 'Enterprise', 'employee_count_range': (72000, 80000), 'is_public': True, 'specialties': ('CRM', 'Cloud platforms', 'Marketing automation', 'AI agents')},
    {'name': 'Oracle', 'legal_name': 'Oracle Corporation', 'industry': 'Enterprise IT', 'website': 'https://www.oracle.com', 'career_page': 'https://www.oracle.com/careers/', 'headquarters_city': 'Austin', 'headquarters_country': 'United States', 'description': 'Oracle delivers database systems, enterprise applications, and cloud infrastructure to large organizations globally.', 'founded_year': 1977, 'company_size': 'Enterprise', 'employee_count_range': (160000, 170000), 'is_public': True, 'specialties': ('Databases', 'Enterprise applications', 'Cloud infrastructure', 'ERP')},
    {'name': 'SAP', 'legal_name': 'SAP SE', 'industry': 'Enterprise IT', 'website': 'https://www.sap.com', 'career_page': 'https://jobs.sap.com', 'headquarters_city': 'Munich', 'headquarters_country': 'Germany', 'description': 'SAP builds enterprise resource planning and business software used by large organizations worldwide.', 'founded_year': 1972, 'company_size': 'Enterprise', 'employee_count_range': (105000, 115000), 'is_public': True, 'specialties': ('ERP', 'Supply chain software', 'Enterprise cloud', 'Analytics')},
    {'name': 'IBM', 'legal_name': 'International Business Machines Corporation', 'industry': 'Enterprise IT', 'website': 'https://www.ibm.com', 'career_page': 'https://www.ibm.com/careers', 'headquarters_city': 'New York', 'headquarters_country': 'United States', 'description': 'IBM provides hybrid cloud, AI, and consulting services to enterprises across industries.', 'founded_year': 1911, 'company_size': 'Enterprise', 'employee_count_range': (280000, 290000), 'is_public': True, 'specialties': ('Hybrid cloud', 'AI consulting', 'Enterprise infrastructure', 'Quantum computing')},
    {'name': 'Cisco', 'legal_name': 'Cisco Systems, Inc.', 'industry': 'Networking', 'website': 'https://www.cisco.com', 'career_page': 'https://jobs.cisco.com', 'headquarters_city': 'San Jose', 'headquarters_country': 'United States', 'description': 'Cisco builds networking, security, and collaboration technology powering the internet’s infrastructure.', 'founded_year': 1984, 'company_size': 'Enterprise', 'employee_count_range': (84000, 92000), 'is_public': True, 'specialties': ('Networking', 'Cybersecurity', 'Collaboration tools', 'Data center')},
    {'name': 'Intel', 'legal_name': 'Intel Corporation', 'industry': 'Semiconductors', 'website': 'https://www.intel.com', 'career_page': 'https://jobs.intel.com', 'headquarters_city': 'Santa Clara', 'headquarters_country': 'United States', 'description': 'Intel designs and manufactures semiconductors, processors, and computing platforms for consumer and enterprise markets.', 'founded_year': 1968, 'company_size': 'Enterprise', 'employee_count_range': (110000, 125000), 'is_public': True, 'specialties': ('Semiconductor design', 'Processor architecture', 'AI accelerators', 'Manufacturing')},
    {'name': 'NVIDIA', 'legal_name': 'NVIDIA Corporation', 'industry': 'Semiconductors', 'website': 'https://www.nvidia.com', 'career_page': 'https://www.nvidia.com/en-us/about-nvidia/careers/', 'headquarters_city': 'Santa Clara', 'headquarters_country': 'United States', 'description': 'NVIDIA designs GPUs and accelerated computing platforms powering gaming, AI, and data center workloads.', 'founded_year': 1993, 'company_size': 'Large', 'employee_count_range': (29000, 34000), 'is_public': True, 'specialties': ('GPU architecture', 'AI infrastructure', 'Accelerated computing', 'Robotics')},
    {'name': 'Uber', 'legal_name': 'Uber Technologies, Inc.', 'industry': 'Mobility', 'website': 'https://www.uber.com', 'career_page': 'https://www.uber.com/us/en/careers/', 'headquarters_city': 'San Francisco', 'headquarters_country': 'United States', 'description': 'Uber operates global ride-hailing, delivery, and freight marketplaces connecting millions of riders and drivers.', 'founded_year': 2009, 'company_size': 'Large', 'employee_count_range': (30000, 35000), 'is_public': True, 'specialties': ('Marketplace platforms', 'Maps and routing', 'Real-time systems', 'Logistics')},
    {'name': 'Airbnb', 'legal_name': 'Airbnb, Inc.', 'industry': 'Consumer Internet', 'website': 'https://www.airbnb.com', 'career_page': 'https://careers.airbnb.com', 'headquarters_city': 'San Francisco', 'headquarters_country': 'United States', 'description': 'Airbnb operates a global marketplace for short-term stays and experiences connecting hosts and travelers.', 'founded_year': 2008, 'company_size': 'Mid-Market', 'employee_count_range': (6500, 7500), 'is_public': True, 'specialties': ('Marketplace platforms', 'Trust and safety', 'Search and ranking', 'Payments')},
    {'name': 'Spotify', 'legal_name': 'Spotify Technology S.A.', 'industry': 'Media Technology', 'website': 'https://www.spotify.com', 'career_page': 'https://www.lifeatspotify.com', 'headquarters_city': 'Berlin', 'headquarters_country': 'Germany', 'description': 'Spotify operates a global audio streaming platform for music and podcasts powered by large-scale recommendation systems.', 'founded_year': 2006, 'company_size': 'Large', 'employee_count_range': (9000, 10500), 'is_public': True, 'specialties': ('Streaming platforms', 'Recommendation systems', 'Audio tech', 'Data engineering')},
    {'name': 'Stripe', 'legal_name': 'Stripe, Inc.', 'industry': 'Fintech', 'website': 'https://stripe.com', 'career_page': 'https://stripe.com/jobs', 'headquarters_city': 'San Francisco', 'headquarters_country': 'United States', 'description': 'Stripe builds payments infrastructure and financial tooling used by millions of internet businesses.', 'founded_year': 2010, 'company_size': 'Large', 'employee_count_range': (8000, 9500), 'is_public': False, 'specialties': ('Payments infrastructure', 'Fintech APIs', 'Fraud prevention', 'Billing systems')},
    {'name': 'Atlassian', 'legal_name': 'Atlassian Corporation', 'industry': 'SaaS', 'website': 'https://www.atlassian.com', 'career_page': 'https://www.atlassian.com/company/careers', 'headquarters_city': 'Sydney', 'headquarters_country': 'Australia', 'description': 'Atlassian builds collaboration and software development tools including Jira, Confluence, and Trello.', 'founded_year': 2002, 'company_size': 'Large', 'employee_count_range': (11000, 12500), 'is_public': True, 'specialties': ('Developer tools', 'Collaboration software', 'Project management', 'DevOps')},

    # --- Finance / banking ---
    {'name': 'JPMorgan Chase', 'legal_name': 'JPMorgan Chase & Co.', 'industry': 'Financial Services', 'website': 'https://www.jpmorganchase.com', 'career_page': 'https://careers.jpmorgan.com', 'headquarters_city': 'New York', 'headquarters_country': 'United States', 'description': 'JPMorgan Chase is a global financial services firm offering investment banking, asset management, and consumer banking, with a large in-house technology organization.', 'founded_year': 1799, 'company_size': 'Enterprise', 'employee_count_range': (290000, 310000), 'is_public': True, 'specialties': ('Investment banking tech', 'Risk systems', 'Trading platforms', 'Cybersecurity')},
    {'name': 'Goldman Sachs', 'legal_name': 'The Goldman Sachs Group, Inc.', 'industry': 'Financial Services', 'website': 'https://www.goldmansachs.com', 'career_page': 'https://www.goldmansachs.com/careers/', 'headquarters_city': 'New York', 'headquarters_country': 'United States', 'description': 'Goldman Sachs is a leading global investment bank and financial services firm with significant engineering and quantitative research teams.', 'founded_year': 1869, 'company_size': 'Enterprise', 'employee_count_range': (45000, 49000), 'is_public': True, 'specialties': ('Quantitative finance', 'Trading systems', 'Risk analytics', 'Cloud engineering')},
    {'name': 'Morgan Stanley', 'legal_name': 'Morgan Stanley', 'industry': 'Financial Services', 'website': 'https://www.morganstanley.com', 'career_page': 'https://www.morganstanley.com/careers', 'headquarters_city': 'New York', 'headquarters_country': 'United States', 'description': 'Morgan Stanley provides investment banking, wealth management, and institutional securities services backed by a large technology division.', 'founded_year': 1935, 'company_size': 'Enterprise', 'employee_count_range': (80000, 85000), 'is_public': True, 'specialties': ('Wealth management tech', 'Trading platforms', 'Data analytics', 'Cloud infrastructure')},
    {'name': 'Visa', 'legal_name': 'Visa Inc.', 'industry': 'Fintech', 'website': 'https://www.visa.com', 'career_page': 'https://www.visa.com/careers', 'headquarters_city': 'San Francisco', 'headquarters_country': 'United States', 'description': 'Visa operates one of the world’s largest electronic payments networks, processing transactions across 200+ countries.', 'founded_year': 1958, 'company_size': 'Large', 'employee_count_range': (26000, 30000), 'is_public': True, 'specialties': ('Payment networks', 'Fraud detection', 'Tokenization', 'Financial APIs')},
    {'name': 'Mastercard', 'legal_name': 'Mastercard Incorporated', 'industry': 'Fintech', 'website': 'https://www.mastercard.com', 'career_page': 'https://careers.mastercard.com', 'headquarters_city': 'New York', 'headquarters_country': 'United States', 'description': 'Mastercard operates global payment technology and financial services connecting consumers, banks, and merchants.', 'founded_year': 1966, 'company_size': 'Large', 'employee_count_range': (33000, 36000), 'is_public': True, 'specialties': ('Payment technology', 'Cybersecurity', 'Data analytics', 'Open banking')},
    {'name': 'HDFC Bank', 'legal_name': 'HDFC Bank Limited', 'industry': 'Financial Services', 'website': 'https://www.hdfcbank.com', 'career_page': 'https://www.hdfcbank.com/personal/about-us/careers', 'headquarters_city': 'Mumbai', 'headquarters_country': 'India', 'description': 'HDFC Bank is one of India’s largest private sector banks, investing heavily in digital banking and fintech platforms.', 'founded_year': 1994, 'company_size': 'Enterprise', 'employee_count_range': (170000, 210000), 'is_public': True, 'specialties': ('Digital banking', 'Core banking systems', 'Mobile banking', 'Risk and compliance tech')},
    {'name': 'ICICI Bank', 'legal_name': 'ICICI Bank Limited', 'industry': 'Financial Services', 'website': 'https://www.icicibank.com', 'career_page': 'https://www.icicicareers.com', 'headquarters_city': 'Mumbai', 'headquarters_country': 'India', 'description': 'ICICI Bank is a leading Indian private bank offering retail and corporate banking with a strong digital-first technology strategy.', 'founded_year': 1994, 'company_size': 'Enterprise', 'employee_count_range': (140000, 150000), 'is_public': True, 'specialties': ('Digital banking', 'Payments infrastructure', 'Data science', 'Core banking')},
    {'name': 'American Express', 'legal_name': 'American Express Company', 'industry': 'Financial Services', 'website': 'https://www.americanexpress.com', 'career_page': 'https://www.americanexpress.com/en-us/careers/', 'headquarters_city': 'New York', 'headquarters_country': 'United States', 'description': 'American Express provides charge cards, payments, and travel services with substantial investment in technology and fraud analytics.', 'founded_year': 1850, 'company_size': 'Enterprise', 'employee_count_range': (74000, 78000), 'is_public': True, 'specialties': ('Payments technology', 'Fraud analytics', 'Customer platforms', 'Machine learning')},

    # --- Healthcare / biotech ---
    {'name': 'UnitedHealth Group', 'legal_name': 'UnitedHealth Group Incorporated', 'industry': 'Healthcare', 'website': 'https://www.unitedhealthgroup.com', 'career_page': 'https://careers.unitedhealthgroup.com', 'headquarters_city': 'Chicago', 'headquarters_country': 'United States', 'description': 'UnitedHealth Group operates health insurance and health services businesses, with Optum powering large-scale healthcare technology platforms.', 'founded_year': 1977, 'company_size': 'Enterprise', 'employee_count_range': (400000, 440000), 'is_public': True, 'specialties': ('Health tech platforms', 'Data analytics', 'Claims processing', 'Population health')},
    {'name': 'Pfizer', 'legal_name': 'Pfizer Inc.', 'industry': 'Biotech', 'website': 'https://www.pfizer.com', 'career_page': 'https://www.pfizer.com/about/careers', 'headquarters_city': 'New York', 'headquarters_country': 'United States', 'description': 'Pfizer is a global biopharmaceutical company researching and manufacturing vaccines and medicines, supported by extensive R&D technology systems.', 'founded_year': 1849, 'company_size': 'Enterprise', 'employee_count_range': (78000, 85000), 'is_public': True, 'specialties': ('Biotech R&D systems', 'Clinical data platforms', 'Manufacturing tech', 'Regulatory informatics')},
    {'name': 'Johnson & Johnson', 'legal_name': 'Johnson & Johnson', 'industry': 'Healthcare', 'website': 'https://www.jnj.com', 'career_page': 'https://www.careers.jnj.com', 'headquarters_city': 'New York', 'headquarters_country': 'United States', 'description': 'Johnson & Johnson develops pharmaceutical and medical technology products with global R&D and manufacturing technology teams.', 'founded_year': 1886, 'company_size': 'Enterprise', 'employee_count_range': (130000, 140000), 'is_public': True, 'specialties': ('Medical device software', 'Clinical systems', 'Supply chain tech', 'R&D data platforms')},
    {'name': 'Moderna', 'legal_name': 'Moderna, Inc.', 'industry': 'Biotech', 'website': 'https://www.modernatx.com', 'career_page': 'https://www.modernatx.com/careers', 'headquarters_city': 'Boston', 'headquarters_country': 'United States', 'description': 'Moderna is a biotechnology company pioneering mRNA therapeutics, backed by significant computational biology and data infrastructure.', 'founded_year': 2010, 'company_size': 'Mid-Market', 'employee_count_range': (5500, 6500), 'is_public': True, 'specialties': ('Computational biology', 'mRNA platform engineering', 'Clinical data science', 'Manufacturing automation')},
    {'name': 'Practo', 'legal_name': 'Practo Technologies Private Limited', 'industry': 'Healthcare', 'website': 'https://www.practo.com', 'career_page': 'https://www.practo.com/careers', 'headquarters_city': 'Bengaluru', 'headquarters_country': 'India', 'description': 'Practo builds digital healthcare platforms connecting patients with doctors, diagnostics, and health records across India.', 'founded_year': 2008, 'company_size': 'Growth', 'employee_count_range': (900, 1400), 'is_public': False, 'specialties': ('Health tech', 'Telemedicine', 'EHR systems', 'Healthcare marketplaces')},

    # --- Retail / consumer / manufacturing ---
    {'name': 'Walmart', 'legal_name': 'Walmart Inc.', 'industry': 'Retail', 'website': 'https://www.walmart.com', 'career_page': 'https://careers.walmart.com', 'headquarters_city': 'Chicago', 'headquarters_country': 'United States', 'description': 'Walmart operates global retail and e-commerce operations, with Walmart Global Tech building large-scale supply chain and commerce platforms.', 'founded_year': 1962, 'company_size': 'Enterprise', 'employee_count_range': (2100000, 2300000), 'is_public': True, 'specialties': ('Retail tech', 'Supply chain systems', 'E-commerce platforms', 'Data engineering')},
    {'name': 'Target', 'legal_name': 'Target Corporation', 'industry': 'Retail', 'website': 'https://www.target.com', 'career_page': 'https://corporate.target.com/careers', 'headquarters_city': 'Chicago', 'headquarters_country': 'United States', 'description': 'Target operates a large retail chain with an in-house technology organization building omnichannel commerce and logistics platforms.', 'founded_year': 1902, 'company_size': 'Enterprise', 'employee_count_range': (400000, 440000), 'is_public': True, 'specialties': ('Omnichannel retail', 'Supply chain tech', 'Data science', 'Mobile commerce')},
    {'name': 'Procter & Gamble', 'legal_name': 'The Procter & Gamble Company', 'industry': 'Manufacturing', 'website': 'https://www.pg.com', 'career_page': 'https://www.pgcareers.com', 'headquarters_city': 'Atlanta', 'headquarters_country': 'United States', 'description': 'P&G manufactures consumer goods globally and runs substantial digital, data, and automation programs across its supply chain.', 'founded_year': 1837, 'company_size': 'Enterprise', 'employee_count_range': (100000, 110000), 'is_public': True, 'specialties': ('Supply chain automation', 'Digital manufacturing', 'Consumer data analytics', 'IoT')},
    {'name': 'Tata Motors', 'legal_name': 'Tata Motors Limited', 'industry': 'Manufacturing', 'website': 'https://www.tatamotors.com', 'career_page': 'https://www.tatamotors.com/careers/', 'headquarters_city': 'Mumbai', 'headquarters_country': 'India', 'description': 'Tata Motors designs and manufactures commercial and passenger vehicles, investing in connected vehicle and EV software platforms.', 'founded_year': 1945, 'company_size': 'Enterprise', 'employee_count_range': (75000, 85000), 'is_public': True, 'specialties': ('Automotive software', 'Connected vehicles', 'EV platforms', 'Manufacturing systems')},
    {'name': 'Siemens', 'legal_name': 'Siemens AG', 'industry': 'Manufacturing', 'website': 'https://www.siemens.com', 'career_page': 'https://jobs.siemens.com', 'headquarters_city': 'Munich', 'headquarters_country': 'Germany', 'description': 'Siemens develops industrial automation, digitalization, and infrastructure technology across manufacturing and energy sectors.', 'founded_year': 1847, 'company_size': 'Enterprise', 'employee_count_range': (310000, 320000), 'is_public': True, 'specialties': ('Industrial automation', 'IoT platforms', 'Digital twins', 'Energy tech')},
    {'name': 'Bosch', 'legal_name': 'Robert Bosch GmbH', 'industry': 'Manufacturing', 'website': 'https://www.bosch.com', 'career_page': 'https://www.bosch.com/careers/', 'headquarters_city': 'Stuttgart', 'headquarters_country': 'Germany', 'description': 'Bosch is a global engineering and technology company producing mobility, industrial, and consumer goods solutions.', 'founded_year': 1886, 'company_size': 'Enterprise', 'employee_count_range': (420000, 430000), 'is_public': False, 'specialties': ('Automotive software', 'IoT and sensors', 'Industrial engineering', 'Embedded systems')},

    # --- Consulting / professional services ---
    {'name': 'Accenture', 'legal_name': 'Accenture plc', 'industry': 'Consulting', 'website': 'https://www.accenture.com', 'career_page': 'https://www.accenture.com/us-en/careers', 'headquarters_city': 'Dublin', 'headquarters_country': 'Ireland', 'description': 'Accenture is a global professional services company providing strategy, consulting, technology, and operations services.', 'founded_year': 1989, 'company_size': 'Enterprise', 'employee_count_range': (735000, 750000), 'is_public': True, 'specialties': ('Technology consulting', 'Cloud transformation', 'Strategy', 'Managed services')},
    {'name': 'Deloitte', 'legal_name': 'Deloitte Touche Tohmatsu Limited', 'industry': 'Consulting', 'website': 'https://www.deloitte.com', 'career_page': 'https://www2.deloitte.com/global/en/careers.html', 'headquarters_city': 'London', 'headquarters_country': 'United Kingdom', 'description': 'Deloitte provides audit, consulting, tax, and advisory services to organizations worldwide with a large digital and technology consulting arm.', 'founded_year': 1845, 'company_size': 'Enterprise', 'employee_count_range': (450000, 470000), 'is_public': False, 'specialties': ('Technology consulting', 'Risk advisory', 'Digital transformation', 'Analytics')},
    {'name': 'McKinsey & Company', 'legal_name': 'McKinsey & Company, Inc.', 'industry': 'Consulting', 'website': 'https://www.mckinsey.com', 'career_page': 'https://www.mckinsey.com/careers', 'headquarters_city': 'New York', 'headquarters_country': 'United States', 'description': 'McKinsey & Company is a global management consulting firm advising organizations on strategy, operations, and digital transformation.', 'founded_year': 1926, 'company_size': 'Large', 'employee_count_range': (38000, 45000), 'is_public': False, 'specialties': ('Strategy consulting', 'Digital transformation', 'Analytics', 'Operations')},
    {'name': 'Capgemini', 'legal_name': 'Capgemini SE', 'industry': 'Consulting', 'website': 'https://www.capgemini.com', 'career_page': 'https://www.capgemini.com/careers/', 'headquarters_city': 'Frankfurt', 'headquarters_country': 'Germany', 'description': 'Capgemini provides consulting, technology, and digital transformation services for enterprises across industries worldwide.', 'founded_year': 1967, 'company_size': 'Enterprise', 'employee_count_range': (340000, 350000), 'is_public': True, 'specialties': ('Digital consulting', 'Cloud engineering', 'Data and AI', 'Application services')},
    {'name': 'Cognizant', 'legal_name': 'Cognizant Technology Solutions Corporation', 'industry': 'Consulting', 'website': 'https://www.cognizant.com', 'career_page': 'https://careers.cognizant.com', 'headquarters_city': 'New York', 'headquarters_country': 'United States', 'description': 'Cognizant provides IT services and consulting, with major delivery centers across India supporting global enterprise clients.', 'founded_year': 1994, 'company_size': 'Enterprise', 'employee_count_range': (335000, 345000), 'is_public': True, 'specialties': ('IT consulting', 'Digital engineering', 'Cloud services', 'AI and automation')},

    # --- Media / entertainment ---
    {'name': 'Disney', 'legal_name': 'The Walt Disney Company', 'industry': 'Media Technology', 'website': 'https://www.disney.com', 'career_page': 'https://jobs.disneycareers.com', 'headquarters_city': 'Los Angeles', 'headquarters_country': 'United States', 'description': 'Disney operates entertainment, media, and streaming businesses, investing heavily in direct-to-consumer streaming technology.', 'founded_year': 1923, 'company_size': 'Enterprise', 'employee_count_range': (220000, 230000), 'is_public': True, 'specialties': ('Streaming platforms', 'Content technology', 'Consumer experiences', 'Data engineering')},
    {'name': 'Sony', 'legal_name': 'Sony Group Corporation', 'industry': 'Media Technology', 'website': 'https://www.sony.com', 'career_page': 'https://www.sony.com/en/SonyInfo/Jobs/', 'headquarters_city': 'Singapore', 'headquarters_country': 'Singapore', 'description': 'Sony builds consumer electronics, gaming, and entertainment platforms including the PlayStation ecosystem.', 'founded_year': 1946, 'company_size': 'Enterprise', 'employee_count_range': (110000, 115000), 'is_public': True, 'specialties': ('Gaming platforms', 'Consumer electronics', 'Entertainment tech', 'Semiconductors')},

    # --- Government-adjacent / public sector tech ---
    {'name': 'National Informatics Centre', 'legal_name': 'National Informatics Centre', 'industry': 'Public Sector Technology', 'website': 'https://www.nic.in', 'career_page': 'https://www.nic.in/recruitment/', 'headquarters_city': 'Delhi NCR', 'headquarters_country': 'India', 'description': 'NIC provides e-governance technology infrastructure and digital services supporting central and state government initiatives across India.', 'founded_year': 1976, 'company_size': 'Large', 'employee_count_range': (4000, 6000), 'is_public': False, 'specialties': ('E-governance platforms', 'Public sector cloud', 'Digital identity systems', 'Data centers')},
    {'name': 'Leidos', 'legal_name': 'Leidos Holdings, Inc.', 'industry': 'Public Sector Technology', 'website': 'https://www.leidos.com', 'career_page': 'https://www.leidos.com/careers', 'headquarters_city': 'Atlanta', 'headquarters_country': 'United States', 'description': 'Leidos provides technology and engineering solutions to defense, intelligence, health, and civil government agencies.', 'founded_year': 1969, 'company_size': 'Large', 'employee_count_range': (46000, 48000), 'is_public': True, 'specialties': ('Defense IT systems', 'Cybersecurity', 'Health IT', 'Cloud modernization')},

    # --- High-growth startups / product companies ---
    {'name': 'Postman', 'legal_name': 'Postman, Inc.', 'industry': 'SaaS', 'website': 'https://www.postman.com', 'career_page': 'https://www.postman.com/company/careers/', 'headquarters_city': 'San Francisco', 'headquarters_country': 'United States', 'description': 'Postman builds the leading API development and collaboration platform used by millions of developers worldwide.', 'founded_year': 2014, 'company_size': 'Growth', 'employee_count_range': (700, 900), 'is_public': False, 'specialties': ('API tooling', 'Developer platforms', 'Collaboration software', 'Testing automation')},
    {'name': 'Chargebee', 'legal_name': 'Chargebee Inc.', 'industry': 'SaaS', 'website': 'https://www.chargebee.com', 'career_page': 'https://www.chargebee.com/careers/', 'headquarters_city': 'Chennai', 'headquarters_country': 'India', 'description': 'Chargebee provides subscription billing and revenue management software for growing SaaS businesses.', 'founded_year': 2011, 'company_size': 'Growth', 'employee_count_range': (900, 1200), 'is_public': False, 'specialties': ('Subscription billing', 'Revenue operations', 'Fintech APIs', 'SaaS infrastructure')},
    {'name': 'Darwinbox', 'legal_name': 'Darwinbox Digital Solutions Private Limited', 'industry': 'SaaS', 'website': 'https://www.darwinbox.com', 'career_page': 'https://www.darwinbox.com/careers', 'headquarters_city': 'Hyderabad', 'headquarters_country': 'India', 'description': 'Darwinbox builds a cloud-native HR technology platform used by enterprises across Asia for talent management.', 'founded_year': 2015, 'company_size': 'Growth', 'employee_count_range': (1000, 1400), 'is_public': False, 'specialties': ('HR tech', 'Talent management', 'Cloud platforms', 'People analytics')},
    {'name': 'Postdata Analytics', 'legal_name': 'Postdata Analytics Inc.', 'industry': 'Data Analytics', 'website': 'https://www.postdata.io', 'career_page': 'https://www.postdata.io/careers', 'headquarters_city': 'Austin', 'headquarters_country': 'United States', 'description': 'Postdata Analytics builds real-time business intelligence and data pipeline tooling for mid-market companies.', 'founded_year': 2017, 'company_size': 'Growth', 'employee_count_range': (400, 600), 'is_public': False, 'specialties': ('Data pipelines', 'Business intelligence', 'Real-time analytics', 'Data governance')},
    {'name': 'Databricks', 'legal_name': 'Databricks, Inc.', 'industry': 'Data Analytics', 'website': 'https://www.databricks.com', 'career_page': 'https://www.databricks.com/company/careers', 'headquarters_city': 'San Francisco', 'headquarters_country': 'United States', 'description': 'Databricks provides a unified data and AI platform built around the lakehouse architecture, used by enterprises for analytics and machine learning.', 'founded_year': 2013, 'company_size': 'Large', 'employee_count_range': (7000, 8500), 'is_public': False, 'specialties': ('Data lakehouse', 'Machine learning platforms', 'Spark engineering', 'Data governance')},
    {'name': 'Snowflake', 'legal_name': 'Snowflake Inc.', 'industry': 'Data Analytics', 'website': 'https://www.snowflake.com', 'career_page': 'https://careers.snowflake.com', 'headquarters_city': 'Denver', 'headquarters_country': 'United States', 'description': 'Snowflake provides a cloud data platform enabling data warehousing, data lakes, and data sharing at scale.', 'founded_year': 2012, 'company_size': 'Large', 'employee_count_range': (7000, 8000), 'is_public': True, 'specialties': ('Cloud data warehousing', 'Data sharing', 'Data engineering', 'Analytics')},
    {'name': 'ThoughtWorks', 'legal_name': 'Thoughtworks, Inc.', 'industry': 'Consulting', 'website': 'https://www.thoughtworks.com', 'career_page': 'https://www.thoughtworks.com/careers', 'headquarters_city': 'Chicago', 'headquarters_country': 'United States', 'description': 'ThoughtWorks is a global technology consultancy known for agile software delivery and engineering excellence practices.', 'founded_year': 1993, 'company_size': 'Large', 'employee_count_range': (10000, 11500), 'is_public': True, 'specialties': ('Agile software delivery', 'Cloud-native engineering', 'DevOps consulting', 'Technology strategy')},
    {'name': 'Palantir Technologies', 'legal_name': 'Palantir Technologies Inc.', 'industry': 'Data Analytics', 'website': 'https://www.palantir.com', 'career_page': 'https://www.palantir.com/careers/', 'headquarters_city': 'Denver', 'headquarters_country': 'United States', 'description': 'Palantir builds data integration and analytics software used by government agencies and large enterprises.', 'founded_year': 2003, 'company_size': 'Large', 'employee_count_range': (3500, 4200), 'is_public': True, 'specialties': ('Data integration', 'Analytics platforms', 'Government tech', 'AI-assisted decision making')},
    {'name': 'MongoDB', 'legal_name': 'MongoDB, Inc.', 'industry': 'Cloud Infrastructure', 'website': 'https://www.mongodb.com', 'career_page': 'https://www.mongodb.com/company/careers', 'headquarters_city': 'New York', 'headquarters_country': 'United States', 'description': 'MongoDB builds the leading general-purpose document database and developer data platform used by modern application teams.', 'founded_year': 2007, 'company_size': 'Mid-Market', 'employee_count_range': (4800, 5500), 'is_public': True, 'specialties': ('Database engineering', 'Developer platforms', 'Cloud infrastructure', 'Distributed systems')},
    {'name': 'Twilio', 'legal_name': 'Twilio Inc.', 'industry': 'Cloud Infrastructure', 'website': 'https://www.twilio.com', 'career_page': 'https://www.twilio.com/en-us/company/jobs', 'headquarters_city': 'San Francisco', 'headquarters_country': 'United States', 'description': 'Twilio provides cloud communications APIs enabling voice, messaging, and email capabilities for developers.', 'founded_year': 2008, 'company_size': 'Mid-Market', 'employee_count_range': (5000, 6000), 'is_public': True, 'specialties': ('Communications APIs', 'Cloud infrastructure', 'Developer platforms', 'Real-time messaging')},
    {'name': 'GitHub', 'legal_name': 'GitHub, Inc.', 'industry': 'Software', 'website': 'https://github.com', 'career_page': 'https://github.com/about/careers', 'headquarters_city': 'San Francisco', 'headquarters_country': 'United States', 'description': 'GitHub operates the world’s leading software development platform, hosting code and enabling collaborative engineering at scale.', 'founded_year': 2008, 'company_size': 'Mid-Market', 'employee_count_range': (3000, 3500), 'is_public': True, 'specialties': ('Developer platforms', 'Version control', 'AI pair programming', 'DevOps')},
    {'name': 'Shopify', 'legal_name': 'Shopify Inc.', 'industry': 'E-commerce', 'website': 'https://www.shopify.com', 'career_page': 'https://www.shopify.com/careers', 'headquarters_city': 'Ottawa', 'headquarters_country': 'Canada', 'description': 'Shopify provides commerce infrastructure and point-of-sale software enabling merchants to build online and physical stores.', 'founded_year': 2006, 'company_size': 'Large', 'employee_count_range': (11000, 12500), 'is_public': True, 'specialties': ('E-commerce platforms', 'Payments', 'Merchant tools', 'Cloud infrastructure')},
    {'name': 'Canva', 'legal_name': 'Canva Pty Ltd', 'industry': 'SaaS', 'website': 'https://www.canva.com', 'career_page': 'https://www.canva.com/careers/', 'headquarters_city': 'Sydney', 'headquarters_country': 'Australia', 'description': 'Canva builds an online design and visual communication platform used by hundreds of millions of people worldwide.', 'founded_year': 2013, 'company_size': 'Large', 'employee_count_range': (4500, 5500), 'is_public': False, 'specialties': ('Design platforms', 'Consumer applications', 'Cloud infrastructure', 'AI-assisted design')},
    {'name': 'Grab', 'legal_name': 'Grab Holdings Limited', 'industry': 'Mobility', 'website': 'https://www.grab.com', 'career_page': 'https://grab.careers', 'headquarters_city': 'Singapore', 'headquarters_country': 'Singapore', 'description': 'Grab operates a superapp across Southeast Asia offering ride-hailing, delivery, and digital financial services.', 'founded_year': 2012, 'company_size': 'Large', 'employee_count_range': (9000, 11000), 'is_public': True, 'specialties': ('Superapp platforms', 'Mobility tech', 'Digital payments', 'Logistics')},
    {'name': 'Revolut', 'legal_name': 'Revolut Ltd', 'industry': 'Fintech', 'website': 'https://www.revolut.com', 'career_page': 'https://www.revolut.com/careers/', 'headquarters_city': 'London', 'headquarters_country': 'United Kingdom', 'description': 'Revolut operates a global digital banking and financial super-app offering payments, trading, and money management.', 'founded_year': 2015, 'company_size': 'Large', 'employee_count_range': (10000, 11500), 'is_public': False, 'specialties': ('Digital banking', 'Payments infrastructure', 'Trading platforms', 'Fraud detection')},
    {'name': 'Wise', 'legal_name': 'Wise plc', 'industry': 'Fintech', 'website': 'https://wise.com', 'career_page': 'https://wise.jobs', 'headquarters_city': 'London', 'headquarters_country': 'United Kingdom', 'description': 'Wise builds international money transfer infrastructure enabling low-cost cross-border payments for individuals and businesses.', 'founded_year': 2011, 'company_size': 'Mid-Market', 'employee_count_range': (5500, 6500), 'is_public': True, 'specialties': ('Cross-border payments', 'Fintech infrastructure', 'Compliance systems', 'Currency exchange')},
    {'name': 'Klarna', 'legal_name': 'Klarna Bank AB', 'industry': 'Fintech', 'website': 'https://www.klarna.com', 'career_page': 'https://www.klarna.com/careers/', 'headquarters_city': 'Berlin', 'headquarters_country': 'Germany', 'description': 'Klarna provides buy-now-pay-later and digital banking services for consumers and merchants across global markets.', 'founded_year': 2005, 'company_size': 'Large', 'employee_count_range': (4500, 5500), 'is_public': False, 'specialties': ('BNPL platforms', 'Consumer fintech', 'Risk modeling', 'Merchant services')},
    {'name': 'Rippling', 'legal_name': 'Rippling People Center Inc.', 'industry': 'SaaS', 'website': 'https://www.rippling.com', 'career_page': 'https://www.rippling.com/careers', 'headquarters_city': 'San Francisco', 'headquarters_country': 'United States', 'description': 'Rippling builds unified workforce management software spanning HR, IT, and finance operations for growing companies.', 'founded_year': 2016, 'company_size': 'Growth', 'employee_count_range': (2500, 3200), 'is_public': False, 'specialties': ('HR tech', 'IT automation', 'Payroll systems', 'Identity management')},
    {'name': 'Notion Labs', 'legal_name': 'Notion Labs, Inc.', 'industry': 'SaaS', 'website': 'https://www.notion.so', 'career_page': 'https://www.notion.so/careers', 'headquarters_city': 'San Francisco', 'headquarters_country': 'United States', 'description': 'Notion builds an all-in-one workspace for notes, docs, and collaboration used by individuals and teams worldwide.', 'founded_year': 2013, 'company_size': 'Growth', 'employee_count_range': (600, 900), 'is_public': False, 'specialties': ('Productivity software', 'Collaboration tools', 'Knowledge management', 'AI writing assistants')},
    {'name': 'Figma', 'legal_name': 'Figma, Inc.', 'industry': 'SaaS', 'website': 'https://www.figma.com', 'career_page': 'https://www.figma.com/careers/', 'headquarters_city': 'San Francisco', 'headquarters_country': 'United States', 'description': 'Figma builds collaborative interface design and prototyping tools used by product teams worldwide.', 'founded_year': 2012, 'company_size': 'Growth', 'employee_count_range': (1300, 1600), 'is_public': False, 'specialties': ('Design tools', 'Real-time collaboration', 'Developer handoff', 'Prototyping')},
    {'name': 'Cred', 'legal_name': 'Dreamplug Technologies Private Limited', 'industry': 'Fintech', 'website': 'https://cred.club', 'career_page': 'https://careers.cred.club', 'headquarters_city': 'Bengaluru', 'headquarters_country': 'India', 'description': 'CRED operates a members-only platform that rewards on-time credit card bill payments and offers financial services.', 'founded_year': 2018, 'company_size': 'Growth', 'employee_count_range': (1000, 1500), 'is_public': False, 'specialties': ('Fintech rewards platforms', 'Credit and lending', 'Consumer apps', 'Risk modeling')},
    {'name': 'Meesho', 'legal_name': 'Fashnear Technologies Private Limited', 'industry': 'E-commerce', 'website': 'https://www.meesho.com', 'career_page': 'https://www.meesho.io/careers', 'headquarters_city': 'Bengaluru', 'headquarters_country': 'India', 'description': 'Meesho operates an e-commerce marketplace enabling small businesses and individual resellers to sell online across India.', 'founded_year': 2015, 'company_size': 'Large', 'employee_count_range': (2500, 3500), 'is_public': False, 'specialties': ('Social commerce', 'Marketplace platforms', 'Logistics tech', 'Reseller networks')},
    {'name': 'Rapido', 'legal_name': 'Roppen Transportation Services Private Limited', 'industry': 'Mobility', 'website': 'https://www.rapido.bike', 'career_page': 'https://www.rapido.bike/careers', 'headquarters_city': 'Bengaluru', 'headquarters_country': 'India', 'description': 'Rapido operates a bike-taxi and mobility platform serving urban commuters across Indian cities.', 'founded_year': 2015, 'company_size': 'Mid-Market', 'employee_count_range': (1500, 2200), 'is_public': False, 'specialties': ('Mobility platforms', 'Maps and routing', 'Fleet management', 'Consumer apps')},
)


# ================================================================================
# 2. UNIVERSITY DATA
# Real universities used by generate_seed_json.py to create University + User +
# Department records. Kept broad across regions (US, India, UK, Canada,
# Australia) so student cohorts feel geographically diverse.
# Schema: name, city, country, dept (list of department names)
# ================================================================================

UNIVERSITY_DATA: tuple[dict[str, object], ...] = (
    # India
    {'name': 'Indian Institute of Technology, Madras', 'city': 'Chennai', 'country': 'India', 'dept': ['Computer Science', 'Electrical Engineering', 'Mechanical Engineering']},
    {'name': 'Indian Institute of Technology, Bombay', 'city': 'Mumbai', 'country': 'India', 'dept': ['Computer Science', 'Information Technology', 'Data Science']},
    {'name': 'Indian Institute of Technology, Delhi', 'city': 'Delhi NCR', 'country': 'India', 'dept': ['Computer Science', 'Electrical Engineering', 'Chemical Engineering']},
    {'name': 'Indian Institute of Technology, Kanpur', 'city': 'Kanpur', 'country': 'India', 'dept': ['Computer Science', 'Mechanical Engineering']},
    {'name': 'Indian Institute of Science', 'city': 'Bengaluru', 'country': 'India', 'dept': ['Computer Science', 'Data Science', 'Electronics Engineering']},
    {'name': 'Anna University', 'city': 'Chennai', 'country': 'India', 'dept': ['Computer Science', 'Information Technology', 'Electronics and Communication']},
    {'name': 'BITS Pilani', 'city': 'Pilani', 'country': 'India', 'dept': ['Computer Science', 'Electrical and Electronics Engineering']},
    {'name': 'Vellore Institute of Technology', 'city': 'Vellore', 'country': 'India', 'dept': ['Computer Science', 'Information Technology', 'Software Engineering']},
    {'name': 'SRM Institute of Science and Technology', 'city': 'Chennai', 'country': 'India', 'dept': ['Computer Science', 'Information Technology']},
    {'name': 'National Institute of Technology, Trichy', 'city': 'Coimbatore', 'country': 'India', 'dept': ['Computer Science', 'Electronics and Communication']},
    {'name': 'Delhi Technological University', 'city': 'Delhi NCR', 'country': 'India', 'dept': ['Computer Science', 'Software Engineering']},
    {'name': 'IIIT Hyderabad', 'city': 'Hyderabad', 'country': 'India', 'dept': ['Computer Science', 'Data Science', 'Computational Linguistics']},
    {'name': 'PSG College of Technology', 'city': 'Coimbatore', 'country': 'India', 'dept': ['Computer Science', 'Information Technology']},
    {'name': 'Amrita Vishwa Vidyapeetham', 'city': 'Kochi', 'country': 'India', 'dept': ['Computer Science', 'Electronics Engineering']},
    # United States
    {'name': 'Stanford University', 'city': 'San Francisco', 'country': 'United States', 'dept': ['Computer Science', 'Electrical Engineering', 'Management Science']},
    {'name': 'Massachusetts Institute of Technology', 'city': 'Boston', 'country': 'United States', 'dept': ['Computer Science', 'Electrical Engineering and Computer Science']},
    {'name': 'University of California, Berkeley', 'city': 'San Francisco', 'country': 'United States', 'dept': ['Computer Science', 'Data Science', 'Industrial Engineering']},
    {'name': 'Carnegie Mellon University', 'city': 'Chicago', 'country': 'United States', 'dept': ['Computer Science', 'Machine Learning', 'Software Engineering']},
    {'name': 'University of Illinois Urbana-Champaign', 'city': 'Chicago', 'country': 'United States', 'dept': ['Computer Science', 'Electrical and Computer Engineering']},
    {'name': 'Georgia Institute of Technology', 'city': 'Atlanta', 'country': 'United States', 'dept': ['Computer Science', 'Computational Media']},
    {'name': 'University of Michigan', 'city': 'Chicago', 'country': 'United States', 'dept': ['Computer Science', 'Information Science']},
    {'name': 'University of Texas at Austin', 'city': 'Austin', 'country': 'United States', 'dept': ['Computer Science', 'Electrical and Computer Engineering']},
    {'name': 'University of Washington', 'city': 'Seattle', 'country': 'United States', 'dept': ['Computer Science and Engineering', 'Information School']},
    {'name': 'Cornell University', 'city': 'New York', 'country': 'United States', 'dept': ['Computer Science', 'Operations Research']},
    {'name': 'Purdue University', 'city': 'Chicago', 'country': 'United States', 'dept': ['Computer Science', 'Industrial Engineering']},
    # United Kingdom
    {'name': 'Imperial College London', 'city': 'London', 'country': 'United Kingdom', 'dept': ['Computing', 'Electrical and Electronic Engineering']},
    {'name': 'University of Oxford', 'city': 'London', 'country': 'United Kingdom', 'dept': ['Computer Science', 'Engineering Science']},
    {'name': 'University of Cambridge', 'city': 'London', 'country': 'United Kingdom', 'dept': ['Computer Science', 'Engineering']},
    {'name': 'University of Manchester', 'city': 'Manchester', 'country': 'United Kingdom', 'dept': ['Computer Science', 'Electrical and Electronic Engineering']},
    {'name': 'University of Edinburgh', 'city': 'Edinburgh', 'country': 'United Kingdom', 'dept': ['Informatics', 'Computer Science']},
    {'name': 'University College London', 'city': 'London', 'country': 'United Kingdom', 'dept': ['Computer Science', 'Data Science']},
    {'name': 'University of Bristol', 'city': 'Bristol', 'country': 'United Kingdom', 'dept': ['Computer Science', 'Engineering Mathematics']},
    # Canada
    {'name': 'University of Toronto', 'city': 'Toronto', 'country': 'Canada', 'dept': ['Computer Science', 'Electrical and Computer Engineering']},
    {'name': 'University of Waterloo', 'city': 'Waterloo', 'country': 'Canada', 'dept': ['Computer Science', 'Software Engineering', 'Systems Design Engineering']},
    {'name': 'University of British Columbia', 'city': 'Vancouver', 'country': 'Canada', 'dept': ['Computer Science', 'Electrical and Computer Engineering']},
    {'name': 'McGill University', 'city': 'Montreal', 'country': 'Canada', 'dept': ['Computer Science', 'Software Engineering']},
    {'name': 'University of Ottawa', 'city': 'Ottawa', 'country': 'Canada', 'dept': ['Computer Science', 'Electrical Engineering']},
    # Australia
    {'name': 'University of Melbourne', 'city': 'Melbourne', 'country': 'Australia', 'dept': ['Computer Science', 'Information Systems']},
    {'name': 'University of Sydney', 'city': 'Sydney', 'country': 'Australia', 'dept': ['Computer Science', 'Software Engineering']},
    {'name': 'Australian National University', 'city': 'Sydney', 'country': 'Australia', 'dept': ['Computer Science', 'Data Science']},
    {'name': 'University of New South Wales', 'city': 'Sydney', 'country': 'Australia', 'dept': ['Computer Science and Engineering', 'Software Engineering']},
    {'name': 'Monash University', 'city': 'Melbourne', 'country': 'Australia', 'dept': ['Information Technology', 'Software Engineering']},
    # Singapore / other
    {'name': 'National University of Singapore', 'city': 'Singapore', 'country': 'Singapore', 'dept': ['Computer Science', 'Information Systems']},
    {'name': 'Nanyang Technological University', 'city': 'Singapore', 'country': 'Singapore', 'dept': ['Computer Science and Engineering', 'Data Science and AI']},
    {'name': 'Technical University of Munich', 'city': 'Munich', 'country': 'Germany', 'dept': ['Informatics', 'Electrical Engineering']},
    {'name': 'Trinity College Dublin', 'city': 'Dublin', 'country': 'Ireland', 'dept': ['Computer Science', 'Engineering']},
)

# Flat name pool (backward-compatible with sampling call sites that only need names)
UNIVERSITY_POOL: tuple[str, ...] = tuple(u['name'] for u in UNIVERSITY_DATA)


# ================================================================================
# 3. COUNTRY -> CITY MAP
# Used for synthetic company offices, job locations, and salary localization.
# ================================================================================

COUNTRY_CITY_MAP: dict[str, tuple[str, ...]] = {
    'India': ('Chennai', 'Bengaluru', 'Hyderabad', 'Pune', 'Mumbai', 'Delhi NCR', 'Coimbatore', 'Kochi', 'Ahmedabad', 'Kolkata'),
    'United States': ('San Francisco', 'Seattle', 'Austin', 'New York', 'Boston', 'Atlanta', 'Chicago', 'Denver', 'Los Angeles', 'Raleigh'),
    'United Kingdom': ('London', 'Manchester', 'Bristol', 'Edinburgh', 'Birmingham', 'Leeds'),
    'Canada': ('Toronto', 'Vancouver', 'Montreal', 'Waterloo', 'Ottawa', 'Calgary'),
    'Germany': ('Berlin', 'Munich', 'Hamburg', 'Frankfurt', 'Stuttgart'),
    'Singapore': ('Singapore',),
    'Australia': ('Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide'),
    'United Arab Emirates': ('Dubai', 'Abu Dhabi'),
    'Ireland': ('Dublin', 'Cork'),
}


# ================================================================================
# 4. SYNTHETIC COMPANY NAME POOLS
# Used by CompanyGenerator to pad the roster beyond the real-company references
# above once the requested company count exceeds len(PUBLIC_COMPANY_REFERENCES).
# ================================================================================

SYNTHETIC_COMPANY_PREFIXES: tuple[str, ...] = (
    'Aurora', 'BluePeak', 'Catalyst', 'Northstar', 'Vertex', 'Nexora', 'Lattice', 'Granite', 'Skyforge', 'Orbit',
    'Cloudline', 'Signal', 'TrueNorth', 'Silverleaf', 'Meridian', 'Vector', 'Bridgeway', 'Innova', 'Quantum', 'Elevate',
    'Aster', 'Pulse', 'Nova', 'Beacon', 'Helix', 'Arcstone', 'Brightpath', 'Coregrid', 'DeltaWave', 'Zenith',
    'Solace', 'Ironclad', 'Fernbank', 'Glasswing', 'Redshift', 'Emberly', 'Kinetic', 'Palladium', 'Rivergate', 'Wavecrest',
)

SYNTHETIC_COMPANY_SUFFIXES: tuple[str, ...] = (
    'Systems', 'Labs', 'Technologies', 'Works', 'Digital', 'Software', 'Solutions', 'Logic', 'Networks', 'Data',
    'Dynamics', 'Cloud', 'Platforms', 'AI', 'Analytics', 'Mobility', 'Ventures', 'Stack', 'Forge', 'Collective',
)
